name: chart_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  dio: 4.0.0
  retrofit: 2.0.0
  fl_chart: 0.36.1
  json_table: 2.0.1
  flutter_json_view: 0.2.1
  intl: 0.17.0
  supercharged: 2.0.0
  bisect:
    git:
      url: git://github.com/Prn-Ice/Bisect.git

  flutter: 
    sdk: flutter

dev_dependencies: 
  retrofit_generator: any
  json_serializable: any
  build_runner: any
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

